version: '2'
secrets:
 openvpn_creds:
  file: /home/pieuser/seedbox/config/ovpn
 rpc_creds:
  file: /home/pieuser/seedbox/config/transmission-credentials.txt
services:
 transmission:
  image: haugene/transmission-openvpn
  container_name: seedbox
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - 12501:12501
    - 9091:9091
    - 8080:8080
    - 1194:1194 
    # - "8888:8888" # proxy support
  volumes:
    - /home/pieuser/seedbox/downloads/:/data # where transmission will store the data
    - /home/pieuser/seedox/config/:/config # where transmission-home is stored
    - /home/pieuser/seedbox/config/vpn/purevpn/:/etc/openvpn/custom/
    - /home/pieuser/seedbox/config/transmission-home/:/config/transmission-home/ 
  environment:
    - OPENVPN_PROVIDER=custom
    - OPENVPN_USERNAME=**None**
    - OPENVPN_PASSWORD=**None**
    - UFW_ALLOW_GW_NET=true
    - OPENVPN_CONFIG=BE-ovpn-udp
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/16
    - PUID=1000
    - PGUID=1000
  secrets:
    - openvpn_creds
    - rpc_creds
 # proxy:
 #  image: haugene/transmission-openvpn-proxy
 #  links:
 #    - transmission
 #  ports:
 #    - 128080:128080
 #  volumes:
 #    - /etc/localtime:/etc/localtime:ro

 # rss:
 #  image: haugene/transmission-rss
 #  links:
 #    - transmission
 #  environment:
 #    - RSS_URL=http://.../xxxxx.rss
